name: Remote build and deploy .NET Core application to Function App github-traffic-insights
on:
  push:
    branches:
    - main

env:
  AZURE_FUNCTIONAPP_NAME: github-traffic-insights
  AZURE_FUNCTIONAPP_PROJECT_PATH: src/FunctionApp/FunctionApp.csproj
  AZURE_FUNCTIONAPP_DIRECTORY: src/FunctionApp
  DOTNET_CORE_VERSION: 10.0.x

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_CORE_VERSION }}

      - name: Restore
        run: dotnet restore ${{ env.AZURE_FUNCTIONAPP_PROJECT_PATH }}

      - name: Build
        run: dotnet build ${{ env.AZURE_FUNCTIONAPP_PROJECT_PATH }} -c Release --no-restore

      - name: Login to Azure (OIDC)
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_769D6E7C14714595A55C126FCBA6F10F }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_A9888FC216074ED59A8F277E59F1CE9E }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_E1157EFFA0F04B6884A324732F3D7A22 }}

      - name: Deploy to Azure Functions (Flex remote build)
        uses: Azure/functions-action@v1
        with:
          app-name: ${{ env.AZURE_FUNCTIONAPP_NAME }}
          package: ${{ AZURE_FUNCTIONAPP_DIRECTORY }}
          remote-build: true
          enable-oryx-build: true
          respect-funcignore: true
