# Docs for the Azure Web Apps Deploy action: https://github.com/azure/functions-action
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy dotnet core project to Azure Function App - github-traffic-insights

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  AZURE_FUNCTIONAPP_PACKAGE_PATH: './src/FunctionApp' # set this to the path to your web app project, defaults to the repository root
  DOTNET_VERSION: '10.0.x' # set this to the dotnet version to use

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write #This is required for requesting the JWT
      contents: read #This is required for actions/checkout

    steps:
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with: 
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Restore dependencies
        run: dotnet restore ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}/FunctionApp.csproj
        
      - name: Publish FunctionApp
        run: dotnet publish ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}/FunctionApp.csproj -c Release -o ./publish
        
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_769D6E7C14714595A55C126FCBA6F10F }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_A9888FC216074ED59A8F277E59F1CE9E }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_E1157EFFA0F04B6884A324732F3D7A22 }}

      - name: Deploy to Azure Functions
        uses: Azure/functions-action@v1
        with: 
          app-name: 'github-traffic-insights'
          slot-name: 'Production'
          package: './publish'
          
